//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.09.01 at 02:14:43 PM MESZ
//

package de.nobio.pfmsim.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resource", propOrder = { "availability", "count", "skill" })
public class Resource {

    protected Double availability = 0.0D;
    @XmlAttribute
    protected Integer count = 0;
    @XmlElement(nillable = true)
    protected List<Skill> skill;

    public Double getAvailability() {
        return availability;
    }

    public void setAvailability(Double availability) {
        this.availability = availability;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public List<Skill> getSkills() {
        if (skill == null) {
            skill = new ArrayList<Skill>();
        }
        return this.skill;
    }

    @Override
    protected Resource clone() throws CloneNotSupportedException {
        Resource r = new Resource();
        r.setAvailability(new Double(availability));
        r.setCount(new Integer(count));
        r.getSkills().addAll(skill);
        return r;
    }

    @Override
    public String toString() {
        return "\n\tResource [availability=" + availability + ", count=" + count + ", skills=" + skill + "]";
    }

}
