//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.09.01 at 02:14:43 PM MESZ
//

package de.nobio.pfmsim.runtime;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import de.nobio.pfmsim.distribution.WeightedDistribution;
import de.nobio.pfmsim.project.Category;
import de.nobio.pfmsim.project.Phase;
import de.nobio.pfmsim.project.Portfolio;
import de.nobio.pfmsim.resource.Period;
import de.nobio.pfmsim.resource.Resource;
import de.nobio.pfmsim.resource.Skill;
import de.nobio.pfmsim.resource.Team;

/**
 */
@XmlRootElement(name = "simulation")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulation", propOrder = { "availability", "iterations", "pause", "planningHorizont", "skillPool", "phasePool", "projectCategoryPool", "teams", "portfolio" })
public class Simulation {

    @XmlElement(required = true)
    private Double availability;

    @XmlElement(required = true)
    private Long iterations;

    @XmlTransient
    private Long actualIteration;

    @XmlElement(required = true)
    private Long pause;

    @XmlElement(required = true, name = "planning_horizont")
    private Long planningHorizont;

    @XmlElement(nillable = true, name = "skill")
    private List<Skill> skillPool;

    @XmlElement(nillable = true, name = "project_category")
    private List<Category> projectCategoryPool;

    @XmlElement(nillable = true, name = "phase")
    private List<Phase> phasePool;

    @XmlElement(nillable = true, name = "team")
    private List<Team> teams;

    @XmlElement(nillable = false, name = "portfolio")
    private Portfolio portfolio;

    @XmlTransient
    private WeightedDistribution<String> projectCategoryDistribution = new WeightedDistribution<String>();

    /**
     * Method getAvailability.
     * @return Double
     */
    public Double getAvailability() {
        return availability;
    }

    /**
     * Method setAvailability.
     * @param availability Double
     */
    public void setAvailability(Double availability) {
        this.availability = availability;
    }

    /**
     * Method getIterations.
     * @return Long
     */
    public Long getIterations() {
        return iterations;
    }

    /**
     * Method getActualIteration.
     * @return Long
     */
    public Long getActualIteration() {
        return actualIteration;
    }

    /**
     * Method setActualIteration.
     * @param actualIteration Long
     */
    public void setActualIteration(Long actualIteration) {
        this.actualIteration = actualIteration;
    }

    /**
     * Method getPause.
     * @return Long
     */
    public Long getPause() {
        return pause;
    }

    /**
     * Method getPlanningHorizont.
     * @return Long
     */
    public Long getPlanningHorizont() {
        return planningHorizont;
    }

    /**
     * Method setIterations.
     * @param iterations Long
     */
    public void setIterations(Long iterations) {
        this.iterations = iterations;
    }

    /**
     * Method getTeams.
     * @return List<Team>
     */
    public List<Team> getTeams() {
        if (teams == null) {
            teams = new ArrayList<Team>();
        }
        return this.teams;
    }

    /**
     * Method getSkillPool.
     * @return List<Skill>
     */
    public List<Skill> getSkillPool() {
        if (skillPool == null) {
            skillPool = new ArrayList<Skill>();
        }
        return this.skillPool;
    }

    /**
     * Method getSkillFromPool.
     * @param ref String
     * @return Skill
     */
    public Skill getSkillFromPool(String ref) {
        Skill skill = null;
        for (Skill s : skillPool) {
            if (ref.equals(s.getId())) {
                skill = s;
                break;
            }
        }
        return skill;
    }

    /**
     * Method getProjectCategoryPool.
     * @return List<Category>
     */
    public List<Category> getProjectCategoryPool() {
        return projectCategoryPool;
    }

    /**
     * Method getProjectCategoryFromPool.
     * @param ref String
     * @return Category
     */
    public Category getProjectCategoryFromPool(String ref) {
        Category category = null;
        for (Category s : projectCategoryPool) {
            if (ref.equals(s.getId())) {
                category = s;
                break;
            }
        }
        return category;
    }

    /**
     * Method getProjectCategoryDistribution.
     * @return WeightedDistribution<String>
     */
    public WeightedDistribution<String> getProjectCategoryDistribution() {
        return projectCategoryDistribution;
    }

    /**
     * Method setProjectCategoryDistribution.
     * @param projectCategoryDistribution WeightedDistribution<String>
     */
    public void setProjectCategoryDistribution(WeightedDistribution<String> projectCategoryDistribution) {
        this.projectCategoryDistribution = projectCategoryDistribution;
    }

    /**
     * Method getPhases.
     * @return List<Phase>
     */
    public List<Phase> getPhases() {
        return phasePool;
    }

    /**
     * Method getPhaseFromPool.
     * @param ref String
     * @return Phase
     */
    public Phase getPhaseFromPool(String ref) {
        Phase phase = null;
        for (Phase s : phasePool) {
            if (ref.equals(s.getId())) {
                phase = s;
                break;
            }
        }
        return phase;
    }

    /**
     * Method getResourceWithSkill.
     * @param skill Skill
     * @param period Period
     * @param workload Long
     * @return Resource
     */
    public Resource getResourceWithSkill(Skill skill, Period period, Long workload) {
        Resource r = null;
        for (int n = 0; n < getTeams().size() && r == null; n++) {
            r = getTeams().get(n).getResourceWithSkill(skill, period, workload);
        }
        return r;
    }

    /**
    
     * @return all resources in all teams */
    public List<Resource> getAllResources() {
        List<Resource> resources = new ArrayList<Resource>();

        for (Team team : getTeams()) {
            resources.addAll(team.getResources());
        }

        return resources;
    }

    /**
     * Method getPortfolio.
     * @return Portfolio
     */
    public Portfolio getPortfolio() {
        return portfolio;
    }

    /**
    
     * @return thoretical capacity of all resources */
    public Double getTotalCapacity() {
        double capacity = 0.0;
        for (Team team : getTeams()) {
            for (Resource res : team.getResources()) {
                capacity += res.getFreeCapacityForNow();
            }
        }
        return capacity;
    }

    /**
     * Method getTotalAllocation.
     * @return Double
     */
    public Double getTotalAllocation() {
        double alloc = 0.0;
        for (Team team : getTeams()) {
            for (Resource res : team.getResources()) {
                alloc += res.getAllocation();
            }
        }
        return alloc;
    }

    /**
     * Method toString.
     * @return String
     */
    @Override
    public String toString() {
        return "Simulation [availability=" + availability + ", iterations=" + iterations + ", pause=" + pause + ", planningHorizont=" + planningHorizont + ", skillPool="
                + skillPool + ", projectCategoryPool=" + projectCategoryPool + ", phasePool=" + phasePool + ", projectCategoryDistribution" + projectCategoryDistribution
                + ", teams=" + teams + ", portfolio=" + portfolio + "]";
    }

}
